server:
  port: 9991

spring:
  boot:
    admin:
      client:
        instance:
          name: app-1
          service-url: http://localhost:9991
        url: http://localhost:9090

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    display-request-duration: true