server:
  port: 9992

spring:
  boot:
    admin:
      client:
        instance:
          name: app-2
          service-url: http://localhost:9992
        url: http://localhost:9090


management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

springdoc:
  swagger-ui:
    display-request-duration: true